services:
  db:
    container_name: db
    image: postgres:15.3-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql15.3/data
  app:
    container_name: app
    image: myapp
    depends_on:
      - db
    environment:
      REAL_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db/postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  db-data: